name = "FisherGeometryDerivations"
uuid = "5b332f43-0e74-4d49-b5e8-a15e038dc96e"
authors = ["Jan Bouwmanm <email@example.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
